# Generated by Django 5.2.3 on 2025-06-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellido',
            new_name='nombreCiudad',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='edad',
            new_name='poblacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre',
        ),
    ]
